Repository RozadoStudioProjectsOP/web_domains_analytics, pull requests merged in 2023-04, with the labels that each got.

#20 Read data from db
  server/controllers/scrapy.js
  server/models/data.js
  server/routes/scrapy.js
Labels: backend

#21 Scrapy Sanitization
  scraper/README.md
  scraper/example.env
  scraper/scraper/pipelines.py
  scraper/scraper/pipelines/count.py
  scraper/scraper/pipelines/frequency.py
  scraper/scraper/pipelines/mongo.py
  scraper/scraper/pipelines/sanitiser.py
  scraper/scraper/settings.py
  scraper/scraper/spiders/spider1.py
Labels: scrapy

#26 Scraped data Histogram
  client/package-lock.json
  client/package.json
  client/src/components/Histogram.js
  client/src/components/Landing.js
  client/src/index.css
Labels: frontend

#24 Login system
  client/example.env
  client/src/assets/facebookImage.png
  client/src/assets/githubImage.png
  client/src/assets/googleImage.png
  client/src/components/Login.js
  client/src/components/NavBar.js
  client/src/components/OAuth/Loginfunc.css
  client/src/components/OAuth/Loginfunc.js
  client/src/components/Register.js
  client/src/contexts/login.js
  client/src/utils/base_url.js
  server/app.js
  server/controllers/auth.js
  server/controllers/passport.js
  server/controllers/scrapy.js
  server/example.env
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/utils/getTokenUserData.js
Labels: enhancement, backend, frontend
