Repository RozadoStudioProjectsOP/web_domains_analytics, pull requests merged in 2023-10, with the labels that each got.

#86 Llama2 pipeline
  client/src/components/Classification.js
  client/src/components/LLama2.js
  client/src/components/Landing.js
  client/src/components/Sentiment.js
  client/src/components/WordCloud.js
  client/src/components/llama2posNeg.js
  client/src/utils/basePosNedData.js
  client/src/utils/classificationBaseData.js
  scraper/domainScraper/items.py
  scraper/domainScraper/pipelines/AI_Sentiment.py
  scraper/domainScraper/pipelines/llama2_sentiment.py
  scraper/domainScraper/pipelines/mongo.py
  scraper/domainScraper/pipelines/ner.py
  scraper/domainScraper/pipelines/web_classification.py
  scraper/domainScraper/settings.py
Labels: scrapy, frontend

#85 Frontend fixes
  client/src/components/Landing.js
  client/src/components/Login.js
  client/src/styles/Search.css
  server/controllers/scrapy.js
Labels: bug, frontend

#84 Detect changes
  client/src/components/Landing.js
  scraper/README.md
  scraper/domainScraper/headerItems.py
  scraper/domainScraper/items.py
  scraper/domainScraper/pipelines/compareHeader.py
  scraper/domainScraper/pipelines/mongo.py
  scraper/domainScraper/settings.py
  scraper/domainScraper/spiders/analytics.py
  scraper/domainScraper/spiders/viewheader.py
  server/controllers/scrapy.js
  server/routes/scrapy.js
Labels: scrapy, backend, frontend
