Repository RozadoStudioProjectsOP/web_domains_analytics, pull requests merged in 2023-03, with the labels that each got.

#5 Basic Frontend
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/BasePage.js
  client/src/components/Login.js
  client/src/components/Main.js
  client/src/components/Register.js
  client/src/components/WordCloud.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/utils/base_url.js
Labels: enhancement

#6 Backend setup
  server/.gitignore
  server/app.js
  server/controllers/auth.js
  server/db/connection.js
  server/example.env
  server/middleware/authRoute.js
  server/models/data.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/utils/getTokenUserData.js
  server/utils/jwt.js
Labels: backend

#3 Scrapy Startup
  scraper/.gitignore
  scraper/scraper/items.py
  scraper/scraper/middlewares.py
  scraper/scraper/pipelines.py
  scraper/scraper/settings.py
  scraper/scraper/spiders/spider1.py
  scraper/scrapy.cfg
Labels: work in progress, scrapy

#13 Scrapy Pipeline
  scraper/.gitignore
  scraper/README.md
  scraper/example.env
  scraper/scraper/items.py
  scraper/scraper/mongo-pipeline.py
  scraper/scraper/pipelines.py
  scraper/scraper/settings.py
  scraper/scraper/spiders/spider1.py
Labels: scrapy

#14 storing scraped data
  server/app.js
  server/controllers/scrapy.js
  server/db/connection.js
  server/example.env
  server/models/data.js
  server/routes/scrapy.js
Labels: backend
